name: ecogest_front
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^14.1.4
  google_fonts: ^6.0.0
  http: ^1.1.0
  provider: ^6.0.5
  rflutter_alert: 2.0.7
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  date_field: ^6.0.0
  flutter_tagging_plus: ^4.0.2
  url_launcher: ^6.2.1
  image_picker: ^1.0.5
  path_provider: ^2.1.1
  web: ^1.1.0
  pusher_channels_flutter: ^2.2.1
  crypto: ^3.0.3
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  rxdart: ^0.28.0
  device_info_plus: ^11.2.0
  flutter_timezone: ^4.0.0
  image: ^4.1.7
  flutter_dotenv: ^5.1.0
  notification_permissions: ^0.6.1
  permission_handler: ^11.3.1
  introduction_screen: ^3.1.12
  pusher_beams: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:  
    - assets/logo/logo-color.png
    - assets/logo/logo-black.png
    - assets/logo/logo-white.png
    - assets/icon/icon-color.png
    - assets/icon/icon-black.png
    - assets/icon/icon-white.png
    - assets/icon/icon-reverse.png
    - assets/
    - assets/trophy/
    - assets/onboarding/
    - assets/404.jpg
    - .env.example
    - .env
  uses-material-design: true
