@startuml

actor       User       as u
participant    FlutterApp    as fa
collections     BackendApi     as ba
database      DB      as db

u -> fa : Enter an email, a username & password 
fa -> ba : HTTP post to login route with email, username & password params
ba -> db : ask to check if email & username aren't used 
ba -> db : if email & username aren't already used: insert in user table: email, username & crypted password 
ba -> fa : HTTP Response & if Response HTTP's statutCode == 200 return token 
fa-> u : if HTTP Response's statutCode == 200  redirection to home, else error message 

@enduml
