@startuml

actor       User       as u
participant    FlutterApp    as fa
collections     BackendApi     as ba
database      DB      as db

u -> fa : Enter an email, a username & password 
fa -> ba : HTTP post to login route with email & password params
ba -> db : ask to check if email isn't used 
db -> ba : if a user is found or NOT
ba -> db : if NOT: insert request with email & crypted password 
ba -> fa : HTTP Response & if Response HTTP's statutCode == 200 return token 
fa-> u : if HTTP Response's statutCode == 200  redirection to home, else error message 

@enduml