@startuml

actor       User       as u
participant    FlutterApp    as fa
collections     BackendApi     as ba
database      DB      as db

u -> fa : Enter his email & password 
fa -> ba : HTTP post to login route with email & password params
ba -> db : Check crenditials
db -> ba : Response  
ba -> fa : HTTP Response & if Response HTTP's statutCode == 200 return token 
fa-> u : if HTTP Response's statutCode == 200  redirection to home, else error message 

@enduml