@startuml

(*) --> "End of action or challenge : user wins some points"
--> points added to category

If "reach new category level ? yes/no" then
--> [Yes] "User get a new trophy"
-->(*)
Endif

(*) -[hidden]-> "End of action or challenge : user wins some points"
-[hidden]-> points added to category
If "reach new global level ? yes/no" then
--> [Yes] "User level up his badge"
-->(*)
Endif

@enduml