@startuml
(*) --> "(button +) Create a post"
--> "Choose between challenge and action"



if "challenge or action"
-d-> [challenge] "Choose a title, a description, upload an image, a category, some hashtags & a difficulty"
--> "choose start & end dates"
--> "button to post"

else 
-d->[action] "Choose a title, a description, upload an image, a category, some hashtags & a difficulty"
--> "button to post"

endif

@enduml