@startuml
left to right direction
actor "user" as u
rectangle AccountView as av {
 rectangle AccountInfo as ud{
  usecase "username" 
  usecase "image" 
  usecase "biography"
rectangle badge as b{
  usecase "title" 
}
rectangle userPostParticipationTotal as uppt{
  usecase "number of post participation" 
}
rectangle pointsTotal as pt{
  usecase "total point all categories" 
}
}

rectangle trophy as t{
  usecase "list of trophies by category" 
}
}

u --> av

@enduml