@startuml
left to right direction
actor "user" as u
actor "author" as a

rectangle PostActions {
  usecase "create" as cp
  usecase "likes" as lp
  usecase "comments" as cl
}

 usecase "notification" as n

a --> cp : creates the post
u --> lp : likes the post
u --> cl : comments the post
lp --> n : generates 
cl --> n : generates 
n --> a : received the notification
@enduml