@startuml
left to right direction
actor :Visitor: as V
actor :User: as U
actor :Admin: as A

usecase "Log in" as (Connect)
usecase "Register" as (Register)

usecase "See the newsfeed" as (Actu)
usecase "Access their notifications" as (Notif)
usecase "Access an explanatory carousel of the application" as (AppInfos)

package "Posts" as (Publi) {
  usecase "Earn points by category when posting an action"
  usecase "Earn points per category after completing a challenge"
  usecase "See ongoing challenges"
  usecase "Subscribe to a challenge created by other users"
  usecase "Invite other users to participate in a created challenge"
  package "See a post" {
    usecase "Display the detail of a post (comment, like)" as (Détail)
    usecase "Like a post" as (Like)
    usecase "Comment a post" as (Comment)
    usecase "Share the post on social media" as (Shared)
  }
  package "Create a challenge" {
    usecase "Add a challenge title and description"
    usecase "Select the category of a challenge"
    usecase "Select the hashtag(s) of a challenge"
    usecase "Select the duration of a challenge"
  }
  package "Create an action" {
    usecase "Add action title and description"
    usecase "Select the category of an action"
    usecase "Select the hastag(s) of an action"
  }
}

package "Search" as (Search) {
  usecase "Find other users"
  usecase "Look for challenges"
}

package "Settings" as (Param) {
  usecase "Access the Privacy Policy"
  usecase "Access the Legal"
  usecase "Choose between dark or light mode"
  usecase "Choose app language"
  usecase "Delete your account"
  usecase "Download your data"
  usecase "Access a FAQ"
  usecase "Contact the DPO about my rights of access and rectification"
  usecase "Log out" as (Disconnect)
}

package "Other users" as (Others) {
  usecase "View another user's profile"
  usecase "Subscribe to another user"
  usecase "Ask to follow another user"
  usecase "Accept/Decline another user's follow request"
}

package "Profile" as (Profile) {
  usecase "Have a public or private account" as (Status)
  usecase "Accept or decline a follow request" as (Follow)
  usecase "View badge overview (status)"
  usecase "View my trophies by categories"
  usecase "Modify profile information (photo, username, password, city, presentation)"
  note right of (Status)
    Public: posts visible 
    to any logged-in user. 
    Private: posts visible 
    only to their followers
  end note
}

package "Backoffice" {
  usecase "Listing & management of all users"
  usecase "View the number of requests per user"
  usecase "CRUD challenge"
  usecase "CRUD trophy"
}

(Connect) --> U

V --> (Connect)
V --> (Register)
V --> (AppInfos)

U --> (Actu)
U --> (Publi)
U --> (Notif)
U --> (Param)
U --> (Search)
U --> (Others)
U --> (Profile)

A --> (Disconnect)
A --> Backoffice
@enduml